dist: xenial
language: c

env:
  global:
  - GCC=gcc-5
  - GXX=g++-5

cache:
  directories:
  - $HOME/.stack/

addons:
  apt:
    packages:
    - libgmp-dev
    - llvm-9-dev
    - clang-9
    sources:
    - llvm-toolchain-xenial-9

before_install:
- mkdir -p ~/.local/bin
- export PATH=$HOME/.local/bin:$PATH
- travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'

install:
- stack --no-terminal --install-ghc test --only-dependencies

script:
- stack --no-terminal test --haddock --no-haddock-deps
